---
# tasks file for 2do_parcial

- name: Crear directorio para alumno
  file:
    path: /tmp/2do_parcial/alumno
    state: directory

- name: Crear directorio para equipo
  file:
    path: /tmp/2do_parcial/equipo
    state: directory

- name: Generar archivo datos_alumno.txt desde template
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: Generar archivo datos_equipo.txt desde template
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: Configurar sudoers para el grupo 2PSupervisores
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "%2PSupervisores ALL=(ALL) NOPASSWD:ALL"
